v=3
model=WideDeep
#model=Deep
#model=Wide
    #--valid_input=../input/valid \
python ./torch-only-train.py \
    --simple_parse=1 \
    --valid_multiplier=10 \
    --deep_final_act=0 \
    --mlp_dims=50 \
    --mlp_drop=0.2 \
    --field_emb=1 \
    --pooling=sum \
    --dense_activation=relu \
    --model=$model \
    --num_epochs=2 \
    --eager=0 \
    --first_interval_epoch=0.1 \
    --valid_interval_epochs=0.5 \
    --train_input=../input/train \
    --valid_input=../input/valid \
    --model_dir=../input/model/v$v/torch.only/base \
    --batch_size=512 \
    --max_feat_len=100 \
    --optimizer=bert-Adam \
    --min_learning_rate=1e-6 \
    --warmup_steps=1000 \
    --learning_rate=0.001 \
